name: presentation
description: presentation module
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../domain/
  # MOBX
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  # FIREBASE
  firebase_crashlytics: ^0.1.3+3
  firebase_analytics: ^5.0.16
  # UI
  cached_network_image: ^2.2.0+1
  material_design_icons_flutter: 4.0.5345
  fluttertoast: ^7.0.1
  flutter_spinkit: ^4.1.2+1
  theme_mode_handler: ^2.0.0
  flutter_svg: ^0.18.0
  google_maps_flutter: ^0.5.30
  # UTILS
  fluro: ^1.6.3
  easy_localization: ^2.3.3
  google_fonts: ^1.1.0
  shared_preferences: ^0.5.8
  geolocator: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0

flutter:
  uses-material-design: true
