name: domain
description: domain module
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UTILS
  get_it: ^4.0.2
  uuid: ^2.2.0
  uni_links: ^0.4.0
  url_launcher: ^5.5.0
  equatable: ^1.1.1
  json_serializable: ^3.3.0
  copy_with_extension: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  copy_with_extension_gen: ^1.2.0

flutter:
  uses-material-design: true
