name: ios workflow

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: pocket-studios/action-setup-firebase@v1
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v1.3.2
        with:
          channel: stable

      - run: |
          flutter pub get
          cd data
          flutter pub get
          cd ../domain
          flutter pub get
          cd ../presentation
          flutter pub get
      #- run: flutter test
      - run: flutter build ios --release --no-codesign --build-number=${GITHUB_RUN_NUMBER}

      # FOR MANUAL DEPLOY, SEE HERE: https://github.com/flutter/flutter/issues/13065#issuecomment-573354427
